cnr-isti-vclab/meshlab

- src/meshlabplugins/filter_screened_poisson/filter_screened_poisson.pro
The project file for screened poisson is lacking linux linker flag -lgomp and post link filter_screened_poisson.xml copying script.
_The libfilter_screened_poisson.xml link is somehow needed for plugin manager to work correctly on linux (`help>about_plugins` menu is empty for screened_poisson plugin without it)_
_mutualinfo, measure, and sketchfab plugins share this problem too_
> Add linux gomp and post link to screened poisson

- src/meshlabplugins/filter_screened_poisson/filter_screened_poisson.xml
In commit 2e8f2a371ffc7995a0509a6f7fc64c943593ef18 the name of the
filter was changed in the .cpp file; however, the name also needs to be
updated in the .xml file.
See also issue #93
> Screened Poisson: update name in xml file

- src/meshlabserver/mainserver.cpp
I use Meshlab to process point clouds for interactive visualization at NREL in Colorado, USA, and had to patch meshlabserver so that point radii are exported correctly. This patch built two months ago, but I was unable to test it against the current meshlab repository because of other build errors.
> Server now exports point radii if available

- src/README.md
> Added linux build example (Ubuntu 16)

- src/meshlabplugins/edit_paint/paintbox.cpp
- src/meshlabplugins/render_gdp/shaderDialog.h
shaderDialog.h:55:21: error: 'QSlider' was not declared in this scope
shaderDialog.h:56:15: error: 'QLineEdit' was not declared in this scope
paintbox.cpp:35:30: error: invalid use of incomplete type 'class QAction'
...
> Add missing Qt includes

- src/common/ml_shared_data_context.cpp
Fixes wrong texture deallocation on mesh layers with multiple textures (to see the issue just load a mesh with more than one texture and then press the reload button).
> Fixed texture deallocation

- src/meshlabplugins/io_base/baseio.cpp
The bit mask has been erroneously checked with logical AND `&&` instead of bitand `&` as done in all other checks nearby.
> Use bitand instead of logical AND for bitmask

- src/meshlabplugins/filter_select/meshselect.cpp
This is a bugfix for issue #500 
Invalidate vertex-face topology of modified meshes after deleting some parts of the mesh. Not doing this can raise an assert in line 1252 of file vcglib/vcg/complex/allocate.h, because some vertex has their cVFp() not updated.
> Fix: Update topology after face deletion

- src/meshlabplugins/edit_paint/edit_paint.h
Parts of the Qt undo functionality were hidden instead of overriden, as the functions were missing `const`. This adds the missing `const` to actually override the intended function.
Also added `override` to all virtual functions to prevent future errors.
> Add const to actually override virtual functions

- src/meshlabplugins/filter_fractal/filter_functors.h
As already writen in cnr-isti-vclab/vcglib#64 I looked at missing virtual destructor warnings as they may point to possible resource leaks. This is the commit that fixes the warnings from MeshLab compilation that are not in VCGLib.
In this case there might be an actual resource leak, as I'm not sure which pointer types are used to delete all subclasses of `Normalized3DFunctor`.
> Add virtual default destructor to base class

- src/meshlabplugins/filter_mutualglobal/alignGlobal.h
If the function is non-void, but no return, then when building with gcc8-c++, an incorrect assembler code is generated that falls in run-time. A more detailed description can be found here http://bugs.altlinux.org/36038.
> Fix no return statement in the non-void function (according g++8)

- src/meshlabplugins/filter_mls/mlssurface.h
`MlsSurface` is an abstract class whose destructor (as well as its constructor) cannot be called directly.
It can be called only on its derived non-abstract classes. Calling `delete` on a pointer of type `MlsSurface *`, pointing to a concrete class (either RIMLS or APSS), needs a `virtual` destructor.
This PR adds the virtual destructor to `MlsSurface` and fixes the bug.
> filter_mls: fixed crash due to deleting a `MlsSurface *` which couldn't

- src/meshlabplugins/filter_colorproc/filter_colorproc.cpp
I fixed the messages in the "Per face quality depending on triangle shape" dialog according to current code.  Old messages were defined for old code in the 2016-12 version. 
This is the new dialog after applying the changes:
> Fix help messages in the Per_Face_Quality dialog

- src/common/GLLogStream.cpp
- src/common/GLLogStream.h
- src/common/interfaces.cpp
- src/common/interfaces.h
- src/meshlab/glarea.cpp
- src/meshlab/glarea.h
I noticed that `vsprintf` was in some places in meshlab and wanted to replace them with `vsnprintf`, which is in standard c++ since c++11, in order to prevent buffer overflows. 
However, I would have to replace it in multiple places an thought I would be nicer to replace the c variadic functions with c++ variadic templates.
I'm not sure if you are open to PRs like that, so I limited myself to just a view files.
> Replace variadic functions with variadic templates

- src/meshlab/main.cpp
- src/meshlabserver/mainserver.cpp
Resolves #474 - and maybe also a few other locations that try to use the alpha channel.
I added the change to the meshlabserver as well, although I am not sure if the server supports creating snapshots - so that part is untested.
> fix: Snapshot w/ transparency on Linux

- .travis.yml
- src/common/pluginmanager.cpp
- src/meshlabplugins/render_gdp/meshrender.cpp
This permits installation of MeshLab system-wide on Linux (resembles a more generalized version of patches in some distributions):
If it doesn't look like we're using "distrib" directory layout (the executable is in "bin"),
- plugins are also searched in `../lib/meshlab/plugins` relative to the executable dir
- shaders are also searched in `../share/meshlab/shaders` relative to the executable dir
This reflects the installation choices made for Debian.
Split into a separate PR for discussion if any.
> Linux dirs

- src/meshlab/mainwindow_RunTime.cpp
This is a fix for issue #525 . It ensures that Direct filters are added to filterHistory as an OldFilterNameParameterValuesPair right after being executed.
Also... many NULL pointers are renamed to C++11 `nullptr` to dismiss some warnings in clang-modernize.
> Fix #525 Add Direct filters to filterHistory

- src/install/meshlab.nsi
The default shell context in NSIS is for the current user. This causes $SMPROGRAMS to put the link in the current user's profile. Other users on the system get no start menu link. This is causing me trouble because I'm trying to deploy Meshlab in a school and by default only the user that installs the application gets the Start Menu shortcuts.
Docs for SetShellVarContext at https://nsis.sourceforge.io/Docs/Chapter4.html
> Put Start shortcuts in allusers profile instead of currentuser

- src/meshlabserver/mainserver.cpp
- src/meshlabserver/meshlabserver.txt
This PR is identical to #445 but has the code cleanups that @cignoni [asked to be accepted](https://github.com/cnr-isti-vclab/meshlab/pull/445#discussion_r337883176)  on Oct 23.
I really need this changes to export .ply files as ascii, so I constantly have to re-apply after each pull.
Merging this PR will allow to close #445
> Meshlabserver ascii output. Code cleanups

- src/meshlabserver/mainserver.cpp
This is a fix to #434 
Before this fix, meshlabserves crashes with input filenames like `input~1.ply`, `input+1.ply` 
Just don't try to validate file paths, because it is a hard task due to several OS supported. In case of non valid path, an error will be produced later when trying to open the file for reading or writing. (Line 631) 
Also: Remove dependence from "../meshlab/mainwindow.h" header, which was included just to read a const string in maximumDedicatedGPUMem(). (Line 729)
Also: Fix lots of unaligned lines due to mixing tab/spaces. (rest of changes, most only whitespace)
> Fix 434 Trivial validation of file paths

- src/meshlabplugins/filter_layer/filter_layer.cpp
This is a fix for a bug produced when executing `meshlabserver -d help.txt`.
The program try to access rasterModel::label() using a null pointer, so meshlabserver crash immediately.
> Fix: Check rastermodel not null

- src/meshlab/main.cpp
If meshlab is invoked with the --help option, it prints the usage, and then it tries to open the "--help" file. The correct behavior is to exit after printing the usage.
> Exit after printing the help message

- src/meshlab/mainwindow_RunTime.cpp
Sometimes meshlab need to temporarily change the current directory, such as when reading textures or materials for a mesh. When doing that, it forgot to do two things tough:
- Adjusting the path to the mesh now that the directory is changed
- Undoing the change of directory when the loading was done
As result, it would get confused and it could not load either the desired file, or subsequent files that were in a different directory.
Here's a little fix for this. To reproduce the bug, and test the fix, one can do (on Linux or Mac) from the command line:
meshlab dir1/file1.ply file2.ply
> Bugfix when changing directory

- src/meshlab/mainwindow_Init.cpp
This is a feature requested by two users in #531 and https://stackoverflow.com/questions/59326287/meshlab-possible-to-export-import-the-current-camera-configuration
Basically it is unclear the purpose of the option "Windows->Copy shot" (which saves current camera settings to clipboard as a small piece of XML).
I have renamed both QActions and added tooltips to explain its purpose. Yo can preview the result of this PR in next screenshots.
Also: Removed build warning on line 946.
Closes  #531
> Rename Windows.Copy_Shot menu and add menu tooltips

- src/meshlab/glarea.cpp
- src/meshlab/glarea.h
- src/meshlab/main.cpp
- src/meshlab/mainwindow.h
- src/meshlab/mainwindow_Init.cpp
- src/meshlab/mainwindow_RunTime.cpp
When doing repetitive work with meshes, I found it very helpful to load a preferred view of the mesh together with the mesh, such as:
meshlab mesh.ply cameraView.xml
rather than opening the mesh, and then zooming around, or loading the view from disk later. 
When multiple meshes and/or views are specified in various order, the meshes are loaded first, and only the last view is set. This  overwrites any calculated view for a particular mesh and the Qt screen drawing (paint event) is triggered only after the meshes are loaded and the view is set. 
This pull request is on top of pull request https://github.com/cnr-isti-vclab/meshlab/pull/541 which appears to be heading towards approval. The only new commit in this pull request is commit …
> Load a camera view when a mesh is loaded

- src/meshlab/glarea.cpp
- src/meshlab/glarea.h
- src/meshlab/mainwindow.h
- src/meshlab/mainwindow_Init.cpp
- src/meshlab/mainwindow_RunTime.cpp
This is discussed in https://github.com/cnr-isti-vclab/meshlab/issues/531
It is also related to: https://github.com/cnr-isti-vclab/meshlab/pull/534
Add the ability to save a view to a file, paralleling the existing ability to read a view from a file.
I tested this quite a bit and it works. This is my first non-trivial commit, so please do let me know if I overlooked anything.
> Add ability to save view to file

- src/common/filterparameter.cpp
- src/meshlab/mainwindow_Init.cpp
My apologies for too many tiny pull requests. I'll try to take a break. :)
The few fixes I am putting here are for:
- Inconsistent indentation.
- Very verbose printing of all the settings at load time, they are hundreds of lines of text, those are available in the preferences settings in the GUI anyway.
- Wording fix: "save from file" becomes "save to file".
- Wording fix: "a xml" becomes "an xml" (in English, the "x" is pronounced "ex", so it sounds better to say "an xml" than "a xml").
- Shortening a tooltip a little bit.
> Fix menu wording and turn off verbose debugging info

- README.md
When users visit the GitHub page, they are much more likely to read the base README.md file than docs/readme.txt, so I merged the latter into the former. 
This doc needs some more eyeballs, as it is the face of the project. I think docs/readme.txt should be wiped, but then all install scripts should use instead this README.md, which is easy to do but it would be a relatively big change.
> Copy docs/readme.txt to the base README.md

- src/meshlab/glarea.h
- src/meshlab/mainwindow_Init.cpp
- src/meshlab/ml_default_decorators.cpp
This follows the thought expressed by Paolo in https://github.com/cnr-isti-vclab/meshlab/issues/549 to allow the users to opt out of notifying developers. With this change, the pop-up asking folks to send an email sharing their amazing experience will still come up, but a check box, if checked, will save user's preference for the pop-up to not come again. 
I also fixed some compiler warnings about unitialized and unused variables. There are plenty more of such things left to sort out.
> Allow the user to opt out from contacting the developers

- src/meshlab/savemaskexporter.h
- src/meshlabplugins/edit_align/edit_align.cpp
- src/meshlabplugins/edit_hole/fgtHole.h
- src/meshlabplugins/edit_measure/edit_measure.cpp
- src/meshlabplugins/filter_camera/filter_camera.cpp
- src/meshlabplugins/filter_isoparametrization/dual_coord_optimization.h
- src/meshlabplugins/filter_isoparametrization/filter_isoparametrization.cpp
- src/meshlabplugins/filter_isoparametrization/local_optimization.h
- src/meshlabplugins/filter_isoparametrization/param_collapse.h
- src/meshlabplugins/filter_isoparametrization/parametrizator.h
- src/meshlabplugins/filter_isoparametrization/tangent_space.h
- src/meshlabplugins/filter_isoparametrization/texcoord_optimization.h
- src/meshlabplugins/filter_meshing/meshfilter.cpp
- src/meshlabplugins/filter_meshing/quadric_simp.cpp
- src/meshlabplugins/io_expe/import_expe.h
- src/plugins_experimental/edit_ocme/src/ocme/multiple_std_iterator.h
- src/plugins_experimental/edit_ocme/src/ocme/ocme_definition.h
Partially directed by the Debian "lintian" tool. (Apparently it has the phrase "allow to" in its blacklist, since it's not grammatically correct.)
> Codespell and typo fixes.

- src/common/gl_defs.h
- src/common/ml_shared_data_context.cpp
- src/common/mlexception.h
- src/meshlab/glarea.cpp
- src/meshlabplugins/decorate_background/decorate_background.cpp
- src/meshlabplugins/decorate_base/decorate_base.cpp
- src/meshlabplugins/decorate_raster_proj/decorate_raster_proj.cpp
- src/meshlabplugins/decorate_shadow/decorate_shader.h
- src/meshlabplugins/edit_align/AlignPairWidget.cpp
- src/meshlabplugins/edit_align/edit_align.cpp
- src/meshlabplugins/edit_mutualcorrs/edit_mutualcorrs.cpp
- src/meshlabplugins/edit_paint/edit_paint.cpp
- src/meshlabplugins/edit_quality/qualitymapper.cpp
- src/meshlabplugins/edit_select/edit_select.cpp
- src/meshlabplugins/filter_ao/filter_ao.cpp
- src/meshlabplugins/filter_color_projection/render_helper.cpp
- src/meshlabplugins/filter_img_patch_param/filter_img_patch_param.cpp
- src/meshlabplugins/filter_mutualglobal/filter_mutualglobal.cpp
- src/meshlabplugins/filter_mutualinfoxml/filter_mutualinfo.cpp
- src/meshlabplugins/filter_sdfgpu/filter_sdfgpu.cpp
- src/meshlabplugins/render_gdp/meshrender.cpp
- src/meshlabplugins/render_radiance_scaling/radianceScalingRenderer.cpp
- src/meshlabserver/mainserver.cpp
- src/plugins_experimental/render_splatpyramid/splat_pyramid.cc
- src/sampleplugins/sample_filtergpu/sample_filtergpu.cpp
Found these while attempting (without success) to build using OpenGL-ES, but these are issues that probably affect desktop GL as well and probably depend on undocumented driver details to work as they do right now.
The last commit standardizes this usage across all plugins, etc. This would make it easier to switch from GLEW to something like GLAD if GLES support is desired in the future. It also makes glew initialization more consistent.
> Fix OpenGL issues

- src/common/CMakeLists.txt
- src/templates/common.cmake
It has no soname, so shouldn't be in the search path.
Came up during Debian packaging.
> Install libmeshlab-common to meshlab lib subdir.

- .github/workflows/CompileWindows.yml
- src/external.cmake
- src/meshlabplugins/filter_qhull/qhull_tools.h
I had already done most of the work in CMake, but had apparently missed editing this header.
> Fix usage of system vs bundled qhull with CMake

- .github/workflows/CompileUbuntu.yml
- install/linux/resources/meshlab.desktop
- src/CMakeLists.txt
This is just the guts of #609, rebased on top of #616, and with one patch (changing the desktop file name - good idea, but the files that were in there were for appimages) dropped.
> Pr609 rebased on #616 and with incorrect patch dropped

- src/meshlabplugins/filter_isoparametrization/filter_isoparametrization.pro
Hi, 
I experience an error when running iso parametrization filter
```
./meshlab: symbol lookup error: ... undefined symbol: GOMP_parallel
```
I found that adding the flag helped.
> Fix compile arg for isoparametrization plugin

- src/external/structuresynth-1.5/ssynth/SyntopiaCore/GLEngine/Raytracer/AtomicCounter.h
GCC:10 complains about missing `climits` header in `ssynt` 
`{os:Linux,dist:Arch,gcc:10.1.0,qt5:5.15.0}`
```cpp
In file included from /build/meshlab/src/meshlab/src/external/structuresynth-1.5/ssynth/SyntopiaCore/GLEngine/Raytracer/AtomicCounter.cpp:1:
/build/meshlab/src/meshlab/src/external/structuresynth-1.5/ssynth/SyntopiaCore/GLEngine/Raytracer/AtomicCounter.h:28:35: error: ‘ULONG_MAX’ was not declared in this scope
28 |    bool wait(unsigned long time = ULONG_MAX) { wcm.lock(); bool w = wc.wait(&wcm,time); wcm.unlock(); return w; }
|                                   ^~~~~~~~~
/build/meshlab/src/meshlab/src/external/structuresynth-1.5/ssynth/SyntopiaCore/GLEngine/Raytracer/AtomicCounter.h:5:1: note: ‘ULONG_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’? …
```
> Fix build against gcc:10.1.0

- src/meshlab/mainwindow_RunTime.cpp
This is discussed in more detail in https://github.com/cnr-isti-vclab/meshlab/issues/706
There appears to be no good reason as to why the layer dialog on the right must disappear temporarily while a new mesh or new project is added, only to come back right after. It redraws the window unnecessarily which is not helping with the user experience. It gets worse when several meshes are open at the same time, as then it makes the layer dialog to flicker on and off several times.
My best guess is that this is a leftover from when the layer code was not robust enough. I now tested it  without hiding it and no harm is done when a new mesh is added, the layer dialog refreshes itself nicely.
> Avoid unnecessarily turning off the layer dialog

- src/CMakeLists.txt
- src/cmake/FindQhull.cmake
- src/external.cmake
The target for the non-reentrant library is Qhull::libqhull, while
Qhull::qhull is the qhull executable.
Set SYSTEM_QHULL so the right header is included for system qhull.
See https://github.com/cnr-isti-vclab/meshlab/issues/678
> Fix qhull cmake lookup

- src/CMakeLists.txt
My desktop environment does not load the menu icon if in /usr/share/icons/pixmaps.
No other app has an icon there, so I assume it was incorrect.
> Install the icon to /usr/share/pixmaps

- .github/workflows/BuildAndRelease.yml
- .github/workflows/BuildWindows.yml
- install/linux/README.md
- install/macos/README.md
- install/windows/README.md
- install/windows/resources/windows_nsis_script.ps1
- install/windows/windows_build.ps1
- install/windows/windows_build_debug.ps1
- install/windows/windows_deploy.ps1
- install/windows/windows_nsis_installer.ps1
- src/README.md
- src/external/muparser_v225/src/muParserTokenReader.cpp
- src/general.pri
- src/meshlab.pro
- src/meshlab/glarea.cpp
- src/meshlab/glarea_setting.cpp
- src/meshlab/mainwindow_RunTime.cpp
- src/meshlabserver/README.md
Found via `codespell v2.0.dev0`
```
codespell -q 3 -S ./src/external,./vcglib,./src/plugins_unsupported/external  -L lod,vertexes
```
> fix typos found in various files

- src/meshlabplugins/decorate_base/decorate_base.cpp
- src/meshlabplugins/edit_hole/fgtBridge.h
- src/meshlabplugins/edit_hole/fgtHole.h
- src/meshlabplugins/edit_mutualcorrs/edit_mutualcorrsDialog.cpp
- src/meshlabplugins/edit_paint/edit_paint.cpp
- src/meshlabplugins/edit_quality/eqhandle.h
- src/meshlabplugins/filter_colorproc/filter_colorproc.cpp
- src/meshlabplugins/filter_fractal/craters_utils.h
- src/meshlabplugins/filter_globalregistration/globalregistration.cpp
- src/meshlabplugins/filter_isoparametrization/texcoord_optimization.h
- src/meshlabplugins/filter_sampling/filter_sampling.cpp
- src/meshlabplugins/filter_screened_poisson/Src/Array.inl
- src/meshlabplugins/filter_trioptimize/curvedgeflip.h
- src/meshlabplugins/filter_voronoi/filter_voronoi.cpp
- src/meshlabplugins/io_3ds/io_3ds.h
- src/meshlabplugins/io_bre/io_bre.cpp
- src/meshlabplugins/io_x3d/util_x3d.h
- src/meshlabplugins/io_x3d/vrml/Scanner.frame
Follow up to #78  
Found via `codespell v2.0.dev0`
```
codespell -q 3 -S ./src/external,./vcglib,./src/plugins_unsupported/external  -L lod,vertexes src/meshlabplugins/
```
Omitted translating 'trasform, traslate, and closests'
> fix typos found in src/meshlabplugins

- distrib/shaders/depthmap.frag
I'm brand new here, but I was trying to use the depthmap.gdp shader and
wasn't seeing the results I expected. Poking around the fragment shader,
I noticed the `gray` value was used for red, green, blue *and* alpha
channels, meaning values towards 0 (black) won't be displayed as
expected. My wild guess is that this worked when the alpha channel was
ignored, but for me on MacOS it was definitely not working.
Using the `gray` value for red/green/blue and 1.0 for alpha fixes it.
> Fix depthmap shader coloring

- scripts/Linux/resources/snap/snap_noversion.yaml
- snapcraft.yaml
- src/common/GLExtensionsManager.cpp
- src/find_system_libs.pri
The [snapcraft-desktop-helpers](https://github.com/ubuntu/snapcraft-desktop-helpers) seem to be deprecated in favour of toolkit specific [extensions](https://forum.snapcraft.io/t/snapcraft-extensions/13486). There is an additional change to make meshlab work on Wayland.
I actually tried to make the xdg-desktop-portal work, as suggested in https://github.com/cnr-isti-vclab/meshlab/issues/466#issuecomment-710119913. According to https://forum.snapcraft.io/t/xdg-desktop-portals/17331, this should work when using extensions but I still could not open files from `/tmp` via the file dialog.
> use snap extension

- src/meshlab/dialogs/about_dialog.ui
The "Help" dialog had a sentence with the word "remember" showing twice, like this:
"Remember that the simplest way to show your appreciation of the MeshLab system is to remember citing it whenever you have used some of its functionalities."
I removed the second occurrence of the word "remember" as it was an unnecessary repetition.
And I also made "functionalities" into "functionality". In English, "functionality" reefers to "totality of functions", so it sounds awkward when plural.
> Remove the repetition of the word "remember"

- src/meshlabplugins/filter_unsharp/filter_unsharp.cpp
Currently order of the options is :
However, the order seems different with the manual describing(second and third),
https://github.com/cnr-isti-vclab/meshlab/blob/f2c399ac8bff483ab661227c38dd09c82cff4d77/src/meshlabplugins/filter_unsharp/filter_unsharp.cpp#L148-L152
Maybe [PyMeshLab](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#re_compute_vertex_normals) should be concerned too.
> Fix order of the parameters (Re-Compute Vertex Normals)

- src/external/e57/src/E57XmlParser.cpp
https://github.com/asmaloney/libE57Format/commit/13f6a16394ce3eb50ea4cd21f31f77f53294e8d0
> [libE57Format] Port upstream fix for gcc:11

- docs/dox/filter.dox
- src/README.md
- src/external/openkinect/examples/cppview.cpp
- src/meshlabplugins/decorate_raster_proj/decorate_raster_proj.cpp
- src/meshlabplugins/edit_align/align/align_parameter.cpp
- src/meshlabplugins/edit_pickpoints/editpickpoints.cpp
- src/meshlabplugins/edit_pickpoints/pickpointsDialog.cpp
- src/meshlabplugins/edit_pickpoints/pickpointsDialog.h
- src/meshlabplugins/filter_isoparametrization/filter_isoparametrization.cpp
- src/meshlabplugins/filter_sample_dyn/filter_sample_dyn.cpp
Found via `codespell -q 3 -S ./src/external,./src/vcglib,./src/plugins_unsupported/external,./unsupported  -L ba,childs,hist,lod,strutture,vertexes`
> Fix various typos

- src/CMakeLists.txt
- src/external/CMakeLists.txt
Commit 7d47760d37b4 ("moving some settings to an apposite cmake file")
moved the `cmake_policy(SET CMP0072 NEW)` from the toplevel scope to the
scope of the included file. For details, see
https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html
Set NO_POLICY_SCOPE when including the file, to move the POLICIES back
to the toplevel scope.
Fixes #1095.
> Fix scope of CMake Policy variables

- src/common/GLExtensionsManager.cpp
This fixes the "crash" when running Meshlab under Wayland.
The "Unknown error" is actually GLEW_ERROR_NO_GLX_DISPLAY, the lookup was missing until recently:
https://github.com/nigels-com/glew/commit/ea2076658a5bdcc300ac8fde025a296b6a7a7817
As `glewContextInit` is not yet in any released GLEW version, keep using `glewInit` but ignore GLEW_ERROR_NO_GLX_DISPLAY. See https://github.com/nigels-com/glew/issues/172
While the first patch allow starting Meshlab, the central `GLArea` is not rendering correctly (i.e stays blank). Probably the FBO is not blitted correctly to the Wayland surface, investigation ongoing.
Also see #738 and #936
> WIP: Add support for Wayland

- src/meshlabplugins/io_base/save_project.cpp
After “binary” case, the `QDomText nd` remains empty.
> Unshadow variable.

- src/meshlabplugins/io_gltf/gltf_loader.cpp
I ran into two issues with a GLB file loading in MeshLab. 
1. First was when the URI was empty for more than one texture, the latter textures would not be applied because textures already had an empty URI name.
2. I then noticed multi texturing wasn't working unless Wedge Textures were used. src\vcglib\wrap\gl\gl_mesh_attributes_multi_viewer_bo_manager.h would call fillchunkMap() only when ATT_WEDGETEXTURE was used, if it was ATT_VERTTEXTURE _chunkmap wrote the same texture for all vertices (based on what I saw in updateBuffersReplicatedPipeline).
I'm not entirely sure if these fixes are fully appropriate, but this is what I had done to get my models loaded.
> gLTF Multitextures

- src/meshlabplugins/io_gltf/gltf_loader.cpp
- src/meshlabplugins/io_gltf/gltf_loader.h
This PR fixes several issues with the glTF loader plugin:
* For meshes that contain texcoords, but do not have a texture assigned, the loader crashed because it did not add texcoords to the mesh but tried to access them.
* For meshes without texcoords, the loader crashed because the index writing code always tried to access them.
* The loader ignored the byteStride attribute of buffer views.
With these fixes applied, the file [textured-mesh.jpg.glb](https://github.com/cnr-isti-vclab/meshlab/files/7009136/textured-mesh.jpg.glb.zip) from #1064 should load properly. (The other file from #1064 isn't a valid glTF file according to the [glTF Validator](https://github.khronos.org/glTF-Validator/)).
I also downloaded the following glTF sample models from …
> glTF loader fixes

- src/meshlab/glarea.cpp
- src/meshlab/glarea_setting.cpp
- src/meshlab/glarea_setting.h
I found the trackball to be very useful for new users. But it can be also be distracting, as it is on top of the mesh.
This proposes a preference to hide or show the trackball. The default did not change. The user still can, as now, show or hide the trackball just for the current session, or set the new preference for future sessions.
> Add preference to show or hide trackball

- src/CMakeLists.txt
- src/meshlabplugins/filter_developability/CMakeLists.txt
- src/meshlabplugins/filter_developability/energy.h
- src/meshlabplugins/filter_developability/energy_grad.h
- src/meshlabplugins/filter_developability/filter_developability.cpp
- src/meshlabplugins/filter_developability/filter_developability.h
- src/meshlabplugins/filter_developability/mesh_utils.h
- src/meshlabplugins/filter_developability/opt.h
- src/meshlabplugins/filter_developability/remeshing.h
Hey there!
This PR adds a new filter for improving the developability of two-manifold triangle meshes, based on the surface modeling approach proposed in the paper '_Developability of triangle meshes_' [DOI 10.1145/3197517.3201303](https://doi.org/10.1145/3197517.3201303)
> Mesh developability optimization filter

- src/meshlabplugins/filter_qhull/filter_qhull.cpp
This is a typo on commented code. Fixing it nevertheless to keep it from propagating if this snippet gets uncommented. :)
> Fix typo to: Re-orient all faces coherently

- src/meshlab/mainwindow_RunTime.cpp
- src/meshlab/multiViewer_Container.cpp
This pull request fixes the issue in #780 , where closing a project window will crash meshlab. The reason for the crash is an inconsistent ownership: when `mvcont` is created, its parent is specified as the `mdiarea`. When `mvcont` is added as a subWindow to the `mdiarea`, the `mdiarea` internally creates a `QMdiSubWindow` and puts `mvcont` as its internal widget, which will also take ownership of mvcont.
I tested the fix on windows 10 (msvc2019) and ubuntu 22.04:
* Open meshlab
* Close the project window
* Open a new project
* Close it again
* Repeatedly open and close, sometimes add meshes
* No crash happened
I couldn't test on MAC. If there are more tests that should be done, let me know and I will try to do them also.
> Meshlab #780: fix crash when closing project window

- scripts/Linux/internal/2c_portable.sh
If there is an error in a previous step of the build process such that $INSTALL_PATH/usr/lib/meshlab is not created, running 2c_portable.sh causes the files incorrect files to be removed. Adding this conditional before attempting to remove files fixes this issue.
> Portable script no longer deletes incorrect files on fail

- src/meshlabplugins/filter_func/filter_func.cpp
Add a link to [muparser help](https://beltoforion.de/en/muparser/features.php#idDef1) in the help of several "per-face/vertex xxx functions" filter dialog, which will be rendered like this:
It's possible to use [muparser built-in functions](https://beltoforion.de/en/muparser/features.php#idDef1) and the following per-face or per-vertex variables:
**x0,y0,z0** for the first vertex position, **x1,y1,z1** for the second vertex position, **x2,y2,z2** for the third vertex position, **nx0,ny0,nz0 nx1,ny1,nz1 nx2,ny2,nz2** for vertex normals, **r0,g0,b0,a0 r1,g1,b1,a1 ** for vertex colors ...
> Link to muparser help in several filter dialogs

- src/meshlabplugins/filter_func/filter_func.cpp
Add two functions to muParse to generate random numbers
* rnd() will generate a random double value in [0.0 .. 1.0) interval
* randInt(n) will generate a random integer value in [0 .. n) interval
Those functions may be used to generate noise custom noise algorithm that can be aplied to geometry, colors, normals, etc. or select a random number of vertex/faces than can be erased/processed in posterior filters.
>  Add rnd() and randInt(n) functions to muparse 

- src/meshlabplugins/filter_func/filter_func.cpp
- src/meshlabplugins/filter_func/filter_func.h
As proposed at #1409 , this PR adds several Bounding-Box variables available to expressions used in muparser.
New tokens (variables):
Bounding Box Size -> xdim ydim zdim
Bounding Box Diag -> bbdiag
Bounding Box min -> xmin ymin zmin
Bounding Box max -> xmax ymax zmax
Bounding Box midpoint -> xmid ymid zmid
It also adds a new function to generate random values:
rnd() -> random value in 0..1 interval
Here is several examples of usage of these variables in several filters. (Please, note that the help text in the form was changed after taking these screenshots)
The input mesh for many examples will be this 10x10 regular grid:
Use rnd() in "Per-vertex geometric function" to add noise to a mesh
Use rnd() to choose a random set of vertex or faces:
Select the vertex which x == xmin
Select the …
> Add bbox-related variables and rnd() function to muparser expressions 

- src/meshlabplugins/filter_cubization/curvedgeflip.h
change "optimizing 3d triangulations using discrete curvature analysis" pdf link
http://www2.in.tu-clausthal.de/~hormann/papers/Dyn.2001.OTU.pdf is not available 
replaced with 
https://www.inf.usi.ch/faculty/hormann/papers/Dyn.2001.OTU.pdf
> change "optimizing 3d triangulations using discrete curvature analysis" pdf link

- resources/linux/meshlab.desktop
Note that this option is expressed as Non-Default. This flag was added in the v1.4 of the desktop entry spec.
> Update meshlab.desktop to request Descrete GPU

- src/meshlabplugins/io_gltf/gltf_loader.cpp
This PR addresses issue #1464 where vertex colors are not loaded properly from gltf files. 
I tested the change on Windows 10 and Ubuntu 22.04 with some gltf files available here:
https://github.com/KhronosGroup/glTF-Sample-Assets
> Use updateDataMask in gltf loader for vertcolor and wedgetexcoord

- scripts/README.md
MacOs was listed as MaxOS. Small typo fix.
> Fixed Typo in README.md

- .mailmap
- docs/man/meshlabserver.1
- src/cmake/FindGMP.cmake
- src/cmake/FindLib3ds.cmake
- src/cmake/FindOpenCTM.cmake
- src/cmake/Findmuparser.cmake
A few small cleanup items in here:
- I updated the CMake modules that come from my large repo to match the upstream.
- I fixed my name/email in a few other files.
- I added a `.mailmap` file - to fix my name/email in the commit history, but also to unify/normalize other committer identities. `git shortlog -s -e` went from 120 lines down to 93  when applying this mailmap file to combine duplicates, etc. There are a few folks who committed with Paolo's email that I don't know a better email for them right now, they are marked accordingly in the file.
> Update CMake modules, name, mailmap
